version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: swiftpet
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@icloud.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_RUNTIME_DIR: /var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    user: root
    volumes:
      - ~/data/pgadmin:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:

networks:
  default:
    name: swiftpet_network
