DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(200),
    HABILIDADES VARCHAR(5000)
);
